module.exports = {
    "hello": "Hello! How can I assist you today?",
    "hi": "Hi there! How can I help you?",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "what is your name": "I'm BinBuddy, your waste management assistant!",
    "bye": "Goodbye! Have a great day!",
    "thanks": "You're welcome! Feel free to ask me anything.",
    "what goes in the green bin": "Green bins are for organic waste like food scraps and garden clippings.",
    "can i recycle glass?": "Yes, glass can be recycled. Place it in the recycling bin.",
    "what should i do with e-waste?": "E-waste should be taken to a designated e-waste recycling center.",
    "can plastic bags go in the recycling bin?": "No, plastic bags should not be placed in the recycling bin. Check for special collection points.",
    "what is hazardous waste?": "Hazardous waste includes items like batteries, paint, and chemicals. Dispose of them at hazardous waste collection sites.",
    "can i compost paper?": "Yes, uncoated paper without heavy inks or chemicals can be composted.",
    "how do i dispose of old clothes?": "Old clothes can be donated, reused, or taken to textile recycling centers.",
    "is food waste recyclable?": "Food waste is not recyclable but can be composted in the green bin.",
    "can i put broken glass in the green bin?": "No, broken glass should go in the recycling bin if clean. Otherwise, wrap it carefully and place it in general waste.",
    "what items are considered recyclable?": "Recyclable items include clean paper, cardboard, plastic bottles, glass containers, and aluminum cans.",
    "what is the blue bin for?": "The blue bin is for recyclables like paper, cardboard, and plastic containers.",
    "how can i reduce waste at home?": "You can reduce waste by reusing items, composting organic waste, and recycling properly.",
    "what should i do with leftover paint?": "Leftover paint should be taken to a hazardous waste disposal center.",
    "can aluminum foil be recycled?": "Yes, aluminum foil can be recycled if it is clean and free from food residue.",
    "what is the best way to compost?": "The best way to compost is to layer green waste like food scraps with brown waste like dried leaves and maintain proper moisture levels.",
    "can i recycle pizza boxes?": "Pizza boxes can be recycled if they are free from grease and food. Otherwise, compost them.",
    "where should i dispose of batteries?": "Batteries should be taken to a battery recycling drop-off point or hazardous waste center.",
    "what is considered organic waste?": "Organic waste includes food scraps, yard waste, and other biodegradable materials."
};